#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 30 23:18:03 CLT 2023
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=1
shaderPack=
enableShaders=true
