#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 27 22:35:35 CLT 2023
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=
enableShaders=true
