#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 09 17:43:10 CLT 2023
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=1
shaderPack=
enableShaders=true
