name = "Waffles-Optimization"
author = "WaffleIBOT"
version = "1.0.2+1.20.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14183a00177f5bd6606c57348b30805008562c12888c9a7a40a1e9d3fbbbd607"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
