#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jul 11 16:10:30 CLT 2023
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=1
shaderPack=
enableShaders=true
